### ISSUE TITLE
Not working under VMware Player 17

### ISSUE THREAD

**Issue by obfuscatedgenerated** [xlfdll/VMXAudioFix#1]
Guest OS: WinXP x64 Pro

Runs but doesn't do anything to help, don't know how I can elaborate.

**Comment by xlfdll** [comment]
Thank you for the feedback.

Right now I cannot test this because my WinXP x64 Pro's audio does not break for some reason 😂.
I will keep this open and try to test it if I can.

I don't know whether it is because I need to compile a 64-bit version 🤔

**Comment by obfuscatedgenerated** [comment]
Lol, that's weird. Good luck!

**Comment by creopard** [comment]
Some positive feedback:

Tested in VMware Pro 17.0.2

- with Guest OS "WinXP SP3 32-bit"
- virtual sound card (ES1371)
- VMware tools v.10.0.12 (legacy version for XP)

 and it works **flawlessly**. 

As soon as I end "VMXAudioFix", the distortions will come back after some moments (as expected).

**Comment by obfuscatedgenerated** [comment]
My XP is SP2 and 64 bit, perhaps that's why?

Edit: actually, I think there never was an SP3 for x64 pro

**Comment by obfuscatedgenerated** [comment]
I disabled virtualisation based security on the host machine (`bcdedit /set hypervisorlaunchtype off`) and now the sound is fine. No fix tools are needed either. (But of course now I can't use WSL2 lol, I'll just have to toggle when needed)

**Comment by xlfdll** [comment]
> My XP is SP2 and 64 bit, perhaps that's why?
> 
> Edit: actually, I think there never was an SP3 for x64 pro

Thank you very much for the later comments!
I will keep an eye for what you mentioned.

Just FYI, Windows XP x64 indeed does not have SP3, because this is actually based on Windows Server 2003 kernel.
So its SP2 is actually similar to Windows Server 2003 x64, not the 32-bit XP. Windows XP's 32-bit and x64 are quite different inside.

In my machine I don't have Virtualization-based Security enabled, but I can still get distorted sound sometimes if I don't use VMXAudioFix. I think inside this part there is something off that caused buffer underrun or some sorts.
I think maybe my program is 32-bit so that it is not effective in x64 system (as it will run under WOW64).
